[project]
name = 'titanic'
version = '0.1.0'
description = 'Учебный ML-проект для соревнования Kaggle Titanic'
readme = 'README.md'
requires-python = '>=3.12'
dependencies = [
    "catboost>=1.2.10",
    "hydra-core>=1.3.6",
    "joblib>=1.6.0",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.0",
    "seaborn>=0.13.2",
    "skorch>=1.4.0",
    "torch>=2.14.0",
]

[build-system]
requires = ['uv_build>=0.12.8,<0.13']
build-backend = 'uv_build'

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "jinja2>=3.1.6",
]
