model:
  _target_: sklearn.svm.SVC

  # RBF позволяет строить нелинейную границу.
  kernel: rbf

  # Штраф за ошибки классификации.
  C: 1.0

  # Автоматический расчет коэффициента ядра.
  gamma: scale