model:
  _target_: sklearn.svm.SVC

  # RBF позволяет строить нелинейную границу.
  kernel: rbf

  # Лучший штраф за ошибки по результатам кросс-валидации.
  C: 10.0

  # Лучший коэффициент RBF-ядра по результатам уточнённого поиска.
  gamma: 0.003
