model:
  _target_: sklearn.svm.SVC

  # RBF позволяет строить нелинейную границу между классами.
  kernel: rbf

  # Лучшие параметры итерации.
  C: 10.0
  gamma: 0.01

search:
  # Маленькое C сильнее ограничивает модель,
  # большое C сильнее штрафует ошибки на обучении.
  C:
    - 0.1
    - 1.0
    - 10.0
    - 100.0

  # Gamma управляет радиусом влияния наблюдений.
  # Большое значение позволяет строить более сложную границу.
  gamma:
    - scale
    - 0.01
    - 0.1
    - 1.0