model:
  _target_: sklearn.svm.SVC

  # Используем нелинейное RBF-ядро.
  kernel: rbf

  # Лучшие параметры итерации.
  C: 10.0
  gamma: 0.003

search:
  # Уточняем C около найденного значения 10.
  C:
    - 3.0
    - 5.0
    - 10.0
    - 20.0
    - 30.0

  # Проверяем меньшие значения gamma,
  # потому что 0.01 было границей предыдущего поиска.
  gamma:
    - 0.001
    - 0.003
    - 0.005
    - 0.01
    - 0.02
    - 0.03